<? use \Icinga\Module\Windows\Helper\Tools; ?>

<?php if (! $this->compact): ?>
    <div class="controls">
        <?= $this->tabs ?>
    </div>
<?php endif ?>
<div class="content">
    <h1>Windows Updates on host <?= $host ?></h1>
    <h3>Pending updates</h3>
    <? if ($pendingUpdates == null) { ?>
        <p><?= $this->translate('No pending updates available.') ?></p>
    <? } else { ?>
        <table class="common-table table-row-selectable" data-base-target="_next">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>KB</th>
                    <th>Downloaded</th>
                    <th>Require Reboot</th>
                </tr>
            </thead>
            <? foreach ($pendingUpdates as $index => $update) { ?>
                <tbody>
                <tr>
                    <td>
                        <?= $this->qlink(
                            $update->getName(),
                            'windows/pendingupdate',
                            array(
                                'host' => $host,
                                'name' => $update->getName(),
                                'date' => $update->getInstalledOn(),
                            ),
                            array(
                                'icon'  => 'clock',
                                'class' => 'action-link'
                            )
                        ) ?>
                    </td>
                    <td>
                        <?= $update->getKBArticles() ?>
                    </td>
                    <td>
                        <? if ($update->getDownloaded() === true) { ?>
                            <i class="icon icon-ok" original-title="Updates have been downloaded"></i>
                        <? } else { ?>
                            <i class="icon icon-download" original-title="Updates require to be downloaded"></i>
                        <? } ?>
                    </td>
                    <td>
                        <? if ($update->getRequireReboot() === true) { ?>
                            <i class="icon icon-attention-circled" original-title="The host is requiring a reboot"></i>
                        <? } else { ?>
                            <i class="icon icon-ok" original-title="No reboot for this udpated required"></i>
                        <? } ?>
                    </td>
                </tr>
                </tbody>
            <? } ?>
        </table>
    <? } ?>

    <h3>Installed updates</h3>
    <? if ($updateHistory === null) { ?>
        <p><?= $this->translate('No updates found.') ?></p>
    <? } else { ?>
    <table class="common-table table-row-selectable" data-base-target="_next">
        <thead>
            <tr>
                <th>Status</th>
                <th>Name</th>
                <th>Install Date</th>
            </tr>
        </thead>
        <? foreach ($updateHistory as $index => $update) { ?>
        <tbody>
            <tr>
                <td>
                    <i class="icon icon-<?= $update->getResultCodeIcon() ?>" original-title="<?= $update->translateResultCode() ?>"></i>
                </td>
                <td>
                    <?= $this->qlink(
                        $update->getName(),
                        'windows/installedupdate',
                        array(
                            'host' => $host,
                            'name' => $update->getName(),
                            'date' => $update->getInstalledOn(),
                        ),
                        array(
                            'class' => 'action-link'
                        )
                    ) ?>
                </td>
                <td><?= Tools::getInstance()->getDateFromPSOutput($update->getInstalledOn()) ?></td>
            </tr>
        </tbody>
        <? } ?>
    </table>
    <? } ?>
</div>