<?
use \Icinga\Module\Windows\Helper\Navigation;
?>

<?php if (! $this->compact): ?>
    <div class="controls">
        <?= $this->tabs ?>
    </div>
<?php endif ?>
<div class="action-bar" data-base-target="_main">
    <?= Navigation::getInstance()->addBackButton($this, 'windows\hotfixes') ?>
</div>
<div class="content">
    <h3>Installed update description</h3>
    <? if ($hotfix === null) { ?>
        <p><?= $this->translate('No hotfix description found.') ?></p>
    <? } else { ?>
        <table class="name-value-table">
            <tbody>
            <tr>
                <th>Hotfix ID</th>
                <td>
                    <?= $hotfix->getId() ?>
                </td>
            </tr>
            <tr>
                <th>Name</th>
                <td>
                    <?= $hotfix->getName() === null ? '-' : $hotfix->getName() ?>
                </td>
            </tr>
            <tr>
                <th>Description</th>
                <td>
                    <?= $hotfix->getDescription() ?>
                </td>
            </tr>
            <tr>
                <th>Status</th>
                <td>
                    <?= $hotfix->getStatus() === null ? '-' : $hotfix->getStatus() ?>
                </td>
            </tr>
            <tr>
                <th>Install Date</th>
                <td>
                    <?= $hotfix->getInstallDate() ?>
                </td>
            </tr>
            <tr>
                <th>Support Url</th>
                <td>
                    <a href="<?= $hotfix->getSupportUrl() ?>" target="_blank"><?= $hotfix->getSupportUrl() ?></a>
                </td>
            </tr>
            <tr>
                <th>Fix Comments</th>
                <td>
                    <?= $hotfix->getFixComment() ?>
                </td>
            </tr>
            <tr>
                <th>Service Pack</th>
                <td>
                    <?= $hotfix->getServicePack() ?>
                </td>
            </tr>
            <tr>
                <th>Installed by</th>
                <td>
                    <?= $hotfix->getInstalledBy() ?>
                </td>
            </tr>
            </tbody>
        </table>
    <? } ?>
</div>