ALTER TABLE host_check_results
    MODIFY COLUMN module VARCHAR(40) NOT NULL DEFAULT '',
    MODIFY COLUMN result LONGTEXT NULL DEFAULT NULL,
    MODIFY COLUMN timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE host_process_list
    MODIFY COLUMN proc_cmd LONGTEXT NULL DEFAULT NULL;

ALTER TABLE host_pending_updates
    MODIFY COLUMN name TEXT NULL DEFAULT NULL,
    MODIFY COLUMN description TEXT NULL DEFAULT NULL,
    MODIFY COLUMN kbarticles TEXT NULL DEFAULT NULL,
    MODIFY COLUMN uninst_note LONGTEXT NULL DEFAULT NULL,
    MODIFY COLUMN superseded_ids TEXT NULL DEFAULT NULL;

ALTER TABLE host_update_history
    MODIFY COLUMN name TEXT NULL DEFAULT NULL,
    MODIFY COLUMN description TEXT NULL DEFAULT NULL;

ALTER TABLE host_hotfix_history
    MODIFY COLUMN name TEXT NULL DEFAULT NULL,
    MODIFY COLUMN description TEXT NULL DEFAULT NULL,
    MODIFY COLUMN status TEXT NULL DEFAULT NULL,
    MODIFY COLUMN fix_comment TEXT NULL DEFAULT NULL,
    MODIFY COLUMN service_pack TEXT NULL DEFAULT NULL;

ALTER TABLE host_hardware_memory
    MODIFY COLUMN description TEXT NULL DEFAULT NULL;

ALTER TABLE host_hardware_disk
    MODIFY COLUMN capabilities TEXT NULL DEFAULT NULL;

ALTER TABLE host_bios
    MODIFY COLUMN bios_version TEXT NULL DEFAULT NULL;

ALTER TABLE host_system
    MODIFY COLUMN name TEXT NULL DEFAULT NULL;

ALTER TABLE host_perf_counter_help
    MODIFY COLUMN help TEXT NULL DEFAULT NULL;

ALTER TABLE host_interfaces
    MODIFY COLUMN network_addresses TEXT NULL DEFAULT NULL;

ALTER TABLE host_service_list
    MODIFY COLUMN dependent_services TEXT NULL DEFAULT NULL,
    MODIFY COLUMN service_handle TEXT NULL DEFAULT NULL,
    MODIFY COLUMN depends_on TEXT NULL DEFAULT NULL;

INSERT INTO windows_schema_migration
    (schema_version, migration_time)
VALUES (2, NOW());
