<?
    use \Icinga\Module\Windows\Helper\Navigation;
    use \Icinga\Module\Windows\Helper\Tools;
?>

<?php if (! $this->compact): ?>
    <div class="controls">
        <?= $this->tabs ?>
    </div>
<?php endif ?>
<div class="action-bar" data-base-target="_main">
    <?= Navigation::getInstance()->addBackButton($this, 'windows\updates') ?>
</div>
<div class="content">
    <h3>Installed update description</h3>
    <? if ($installedupdate === null) { ?>
        <p><?= $this->translate('No update description found.') ?></p>
    <? } else { ?>
        <table class="name-value-table">
            <tbody>
                <tr>
                    <th>Name</th>
                    <td>
                        <?= $installedupdate->getName() ?>
                    </td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>
                        <?= $installedupdate->getDescription() ?>
                    </td>
                </tr>
                <tr>
                    <th>Support Url</th>
                    <td>
                        <a href="<?= $installedupdate->getSupportUrl() ?>" target="_blank"><?= $installedupdate->getSupportUrl() ?></a>
                    </td>
                </tr>
                <tr>
                    <th>Status</th>
                    <td>
                        <i class="icon icon-<?= $installedupdate->getResultCodeIcon() ?>" original-title="<?= $installedupdate->translateResultCode() ?>"></i>
                    </td>
                </tr>
                <tr>
                    <th>Installed on</th>
                    <td><?= Tools::getInstance()->getDateFromPSOutput($installedupdate->getInstalledOn()) ?></td>
                </tr>
            </tbody>
        </table>
    <? } ?>
</div>