<? use \Icinga\Module\Windows\Helper\Tools; ?>

<?php if (! $this->compact): ?>
    <div class="controls">
        <?= $this->tabs ?>
    </div>
<?php endif ?>
<div class="content">
    <h1>Installed Hotfixes on host <?= $host ?></h1>
    <? if ($hotfixes === null) { ?>
        <p><?= $this->translate('No installed hotfixes found.') ?></p>
    <? } else { ?>
        <table class="common-table table-row-selectable" data-base-target="_next">
            <thead>
            <tr>
                <th>ID</th>
                <th>Description</th>
                <th>Install Date</th>
            </tr>
            </thead>
            <? foreach ($hotfixes as $index => $hotfix) { ?>
                <tbody>
                <tr>
                    <td>
                        <?= $this->qlink(
                            $hotfix->getId(),
                            'windows/hotfix',
                            array(
                                'host' => $host,
                                'id'   => $hotfix->getId(),
                                'date' => $hotfix->getInstallDate()
                            ),
                            array(
                                'icon'  => 'history',
                                'class' => 'action-link'
                            )
                        ) ?>
                    </td>
                    <td>
                        <?= $hotfix->getDescription() ?>
                    </td>
                    <td>
                        <?= $hotfix->getInstallDate() ?>
                    </td>
                </tr>
                </tbody>
            <? } ?>
        </table>
    <? } ?>
</div>