<? use \Icinga\Module\Windows\Helper\Tools; ?>

<?php if (! $this->compact): ?>
    <div class="controls">
        <?= $this->tabs ?>
    </div>
<?php endif ?>
<div class="content">
    <? if ($processList->getProcessList() === null) { ?>
        <p><?= $this->translate('No active processes could be loaded.') ?></p>
    <? } else { ?>
        <table class="common-table table-row-selectable" data-base-target="_next">
            <thead>
            <tr>
                <th>Process</th>
                <th>Instances</th>
                <th>Threads</th>
                <th>Processor in %</th>
                <th>Memory Usage</th>
            </tr>
            </thead>
        <? foreach ($processList->getProcessList() as $index => $process) { ?>
            <tbody>
                <tr>
                    <td>
                        <?= $this->qlink(
                            $index,
                            'windows/process',
                            array(
                                'host'    => $host,
                                'process' => $index
                            ),
                            array(
                                'icon'  => 'tasks',
                                'class' => 'action-link'
                            )
                        ) ?>
                    </td>
                    <td>
                        <?= $processList->getProcessCount($index) ?>
                    </td>
                    <td>
                        <?= $processList->getProcessTotalThreads($index) ?>
                    </td>
                    <td>
                        <?= $processList->getProcessTotalProcessorPercent($index) ?>
                    </td>
                    <td>
                        <?= round(Tools::getInstance()->convertBytesToMB($processList->getProcessTotalUsedMemory($index)), 2) ?> MB
                    </td>
                </tr>
            </tbody>
        <? } ?>
        </table>
    <? } ?>
</div>