<?
    use \Icinga\Module\Windows\Helper\Tools;
    use \Icinga\Module\Windows\Helper\Navigation;
?>

<?php if (! $this->compact): ?>
    <div class="controls">
        <?= $this->tabs ?>
    </div>
<?php endif ?>
<div class="action-bar" data-base-target="_main">
    <?= Navigation::getInstance()->addBackButton($this, 'windows\processes') ?>
</div>
<div class="content">
    <h1>Active <?= $process ?> processes</h1>
    <? if ($processContent === null) { ?>
        <p><?= $this->translate('No processes running for this process.') ?></p>
    <? } else { ?>
        <table class="common-table">
            <thead>
                <tr>
                    <th>Binary</th>
                    <th>Process Id</th>
                    <th>Priority</th>
                    <th>Processor in %</th>
                    <th>Threads</th>
                    <th>Used Memory</th>
                    <th>Required Memory</th>
                    <th>Command Line</th>
                </tr>
            </thead>
            <? foreach ($processContent as $process => $proc) { ?>
                <tbody>
                <td> <?= $proc->getName() ?> </td>
                <td> <?= $proc->getProcessId() ?> </td>
                <td> <?= $proc->getPriority() ?> </td>
                <td>
                    <?= $proc->getProcessorPercent(true) ?>
                </td>
                <td>
                    <?= $proc->getThreadCount() ?>
                </td>
                <td> <?= round(Tools::getInstance()->convertBytesToMB($proc->getUsedMemory()), 2) ?> MB </td>
                <td> <?= round(Tools::getInstance()->convertBytesToMB($proc->getWorkingSetSize()), 2) ?> MB</td>
                <td> <?= $proc->getCMDLine() ?> </td>
                </tbody>
            <? } ?>
        </table>
    <? } ?>
</div>